// all conversation states for the whatsapp bot

export const States = {
    // onboarding
    INITIAL: 'INITIAL',
    ASKING_NAME: 'ASKING_NAME',
    ASKING_EMAIL: 'ASKING_EMAIL',
    ASKING_DOB: 'ASKING_DOB',
    ASKING_ADDRESS: 'ASKING_ADDRESS',

    // plaid bank connection
    INITIATING_PLAID: 'INITIATING_PLAID',
    SELECTING_BANK: 'SELECTING_BANK',
    PLAID_CONNECTING: 'PLAID_CONNECTING',
    CONFIRMING_PLAID_BANK: 'CONFIRMING_PLAID_BANK',

    // recipient management
    RECIPIENT_SELECTION: 'RECIPIENT_SELECTION',
    ASKING_RECIPIENT_NAME: 'ASKING_RECIPIENT_NAME',
    ASKING_PAYMENT_METHOD: 'ASKING_PAYMENT_METHOD',
    ASKING_UPI_ID: 'ASKING_UPI_ID',
    ASKING_ACCOUNT_NUMBER: 'ASKING_ACCOUNT_NUMBER',
    ASKING_IFSC: 'ASKING_IFSC',
    ASKING_BANK_NAME: 'ASKING_BANK_NAME',
    CONFIRMING_RECIPIENT: 'CONFIRMING_RECIPIENT',

    // transfer flow
    ASKING_AMOUNT: 'ASKING_AMOUNT',
    SHOWING_QUOTE: 'SHOWING_QUOTE',
    BANK_ACCOUNT_SELECTION: 'BANK_ACCOUNT_SELECTION',
    CONFIRMING_TRANSFER: 'CONFIRMING_TRANSFER',

    // idle state after transfer or for returning users
    IDLE: 'IDLE'
} as const;

export type StateType = typeof States[keyof typeof States];
